### ISSUE TITLE
glslang doesn't recognize #version correctly

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/glslang#1529]
I'm trying to embed `glslang` into my program so my users can write shaders in GLSL or HLSL, then I can compile them to SPIR-V for use with Vulkan. However, I keep getting errors about `#version` not being the first token in my shader, even though it very definitely is

You can see my code at https://github.com/NovaMods/nova-renderer/blob/rewrite/native/src/loading/shaderpack/shaderpack_loading.cpp#L314. I create a `TShader`, set a few options for the source language and target language, then call `TShader::parse`. Based on the few comments I could find in the code, this seems to be the recommended flow. However, if I'm doing something wrong here, please let me know.

The shader in question is https://github.com/NovaMods/nova-renderer/blob/rewrite/native/tests/resources/shaderpacks/DefaultShaderpack/shaders/gui.vert. As you can see, it's well-formed GLSL that shouldn't cause any problems.

Problem is, I get the following messages from the shader error log:
```
ERROR: 0:1: '64-bit literal' : not supported for this version or the enabled extensions
ERROR: 0:1: '#version' : must occur first in shader
ERROR: 0:1: '#version' : must be followed by version number
ERROR: 0:1: '#version' : bad profile name; use es, core, or compatibility
ERROR: 0:1: '#version' : bad tokens following profile -- expected newline
ERROR: 0:1: '' : compilation terminated
ERROR: 6 compilation errors.  No code generated.
```

What gives? Why is `glslang` telling me that my shader is missing `#version` when it very clearly is not?

**Comment by johnkslang** [comment]
My first guess is there is a mismatched expectation around preambles.  There is handling for user preambles (e.g., to support -D and -U) and the built-in preamble (e.g., setting all the built-in #define etc.). If the #version got consumed as a preamble, it would appear missing.  (That is: first line of shader internally != first line of shader from the user.)

I would look in a debugger around https://github.com/KhronosGroup/glslang/blob/4685f3246e141c168d3eca88a78641ed0e427ec0/glslang/MachineIndependent/ShaderLang.cpp#L805 for verifying that, and lead up to https://github.com/KhronosGroup/glslang/blob/4685f3246e141c168d3eca88a78641ed0e427ec0/StandAlone/StandAlone.cpp#L974 for how the standalone app gets this lined up.

**Comment by DethRaid** [comment]
I've found my issue, through a careful application of the Visual Studio debugger

The way I was loading my shader from disk removed newline characters, so `glslang` saw the entire shader as the `#version` line. Changing my file loader to preserve newlines has solved this issue

Thanks for pointing me in the right direction!
