### PR TITLE
Unbreak build on FreeBSD with GCC/libstdc++ 6.2.0

### PR DESCRIPTION
**Pull request by jbeich**
Probably affects Linux as well with non-standard libc that doesn't bootleg `<stdarg.h>`.
```c++
In file included from C:/Projects/glslang/glslang/MachineIndependent/glslang.y:59:0:
glslang/MachineIndependent/ParseHelper.h:276:24: error: 'va_list' has not been declared
                        va_list args);
                        ^~~~~~~
```

### CODE REVIEW

**Comment by johnkslang** [comment]
Note this fixes issue #636. I've verified it works on VS.
