### ISSUE TITLE
Confusing error when compiling GLSL file as HLSL

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#834]
For example, if x.vert is:
```
#version 450

void main() {
 gl_Position = vec4(1.0);
}
```

Then compiling `glslangValidator -D -V x.vert` yields
```
x.vert
ERROR: x.vert:1: '#version' : must occur first in shader 
ERROR: x.vert:1: '#version' : bad profile name; use es, core, or compatibility 
ERROR: x.vert:1: '#version' : bad tokens following profile -- expected newline 
ERROR: 3 compilation errors.  No code generated.


WARNING: Linking vertex stage: Entry point not found

SPIR-V is not generated for failed compile or link
```

Caused by commit https://github.com/KhronosGroup/glslang/commit/6fa17641b5b5181856a47fa42659bdc7f64edc3d 

I think it's caused by the change to ShaderLang.cpp
https://github.com/KhronosGroup/glslang/commit/6fa17641b5b5181856a47fa42659bdc7f64edc3d#diff-3ae2a2241cce59712e4974622ca1fbb6

The new behaviour is that if compiling for HLSL, it no longer scans for the #version string, and so versionNotFirst is true, versionNotFound is true, and versionWillBeError is true.
That causes Pp.cpp to issue the 'must occur first in shader' error when it encounters '#version' in the source.

It's a valid error but somewhat misleading since HLSL doesn't support #version as far as I know.

The old error was something like this:
```
y.vert:4: error: 'gl_Position' : unknown variable
y.vert:4: error: 'vec4' : no matching overloaded function found
y.vert:4: error: '' : could not create assignment
y.vert: y.vert(4): error at column 25, HLSL parsing failed.
3 errors generated.
```

Low priority from my perspective. This does not block me.

**Comment by johnkslang** [comment]
Note we aren't attempting to write or test for HLSL validation, but fixing the confusing message was easy enough.  You should now see

```
'#version' : invalid preprocessor command
```
