### ISSUE TITLE
Conditional compilation is not handled correctly

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/glslang#3582]
Compiling the following shader:

```glsl
#version 430 core

void main()
{
#if 0
#   define MACROS(S) #S
#endif
}
```

fails with the following error :

```
ERROR: 0:6: '#' : (#) can be preceded in its line only by spaces or horizontal tabs 
ERROR: 0:7: '' : missing #endif 
ERROR: 0:7: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
```

This is a regression that was introduced by https://github.com/KhronosGroup/glslang/commit/feb54379427093dca566cbea996e7a57b80d73eb

**Comment by arcady-lunarg** [comment]
Fixed by #3708

**Comment by TheMostDiligent** [comment]
@arcady-lunarg Thank you!
