### ISSUE TITLE
Fails to compile when nv extensions are disabled.

### ISSUE THREAD

**Issue by mattparks** [KhronosGroup/glslang#1347]
When 'ENABLE_NV_EXTENSIONS' in cmake is set to OFF, glslang fails to compile, I noticed this after commit https://github.com/KhronosGroup/glslang/commit/e891afacf4e87b7274b97ba642891990750d6732. If 'ENABLE_NV_EXTENSIONS' is ON everything compiles and works fine.

```
C:\Users\mattp\Documents\Flounder Workspace\Flounder\Libraries\glslang\glslang\MachineIndependent\ParseHelper.cpp: In member function 'virtual void glslang::TParseContext::finish()':
C:\Users\mattp\Documents\Flounder Workspace\Flounder\Libraries\glslang\glslang\MachineIndependent\ParseHelper.cpp:3982:58: error: 'E_SPV_NV_geometry_shader_passthrough' was not declared in this scope
     if (language == EShLangGeometry && extensionTurnedOn(E_SPV_NV_geometry_shader_passthrough)) {
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
