### ISSUE TITLE
Can't compile with GCC-5.4

### ISSUE THREAD

**Issue by latot** [KhronosGroup/glslang#642]
Hi all, here a little problem when i try compile this:

```
make
[  2%] Building CXX object glslang/CMakeFiles/glslang.dir/MachineIndependent/intermOut.cpp.o
In file included from /home/pipe/Documentos/git/ppsspp/ext/glslang/glslang/MachineIndependent/../Include/InfoSink.h:39:0,
                 from /home/pipe/Documentos/git/ppsspp/ext/glslang/glslang/MachineIndependent/intermOut.cpp:38:
/home/pipe/Documentos/git/ppsspp/ext/glslang/glslang/MachineIndependent/intermOut.cpp: In function ‘bool {anonymous}::is_positive_infinity(double)’:
/home/pipe/Documentos/git/ppsspp/ext/glslang/glslang/MachineIndependent/intermOut.cpp:52:15: error: expected unqualified-id before ‘(’ token
   return std::isinf(x) && (x >= 0);
               ^
glslang/CMakeFiles/glslang.dir/build.make:374: recipe for target 'glslang/CMakeFiles/glslang.dir/MachineIndependent/intermOut.cpp.o' failed
make[2]: *** [glslang/CMakeFiles/glslang.dir/MachineIndependent/intermOut.cpp.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'glslang/CMakeFiles/glslang.dir/all' failed
make[1]: *** [glslang/CMakeFiles/glslang.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Note, i found this from ppsspp project, but i try compile this in the master branch of here and still persist.

Thx. Cya.

**Comment by johnkslang** [comment]
How do you get std::isinf functionality on GCC-5.4?  Is it a GCC bug, or something else? Looking for recommendations.

**Comment by latot** [comment]
Hi, sadly i can't understand very well your question..., the only i do is set gcc-5.4 ver to compile in the system, but how gcc is working or applying the functionality ```std::isinf``` i don't know...

Or if you some other info feel free to ask.

Thx. Cya.

**Comment by steve-lunarg** [comment]
For what it's worth, I'm also using gcc 5.4, and not seeing any problems with that line.

```
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

I also tried std::isinf in a standalone program and it seems to be fine.  I'd suspect a local configuration or installation issue of some sort.  Here's the standalone program I tried, if the original poster wants to see if it has the same problem.
```
#include <cmath>
int main()
{
    std::isinf(5.0);
    return 0;
}
```

**Comment by latot** [comment]
Hi, that example works fine, following a recommendation from the issue in ppsspp this can be fixed with this, in the file change:
```
#ifdef _MSC_VER
#include <float.h>
#else
#include <math.h>
#endif
```
to
```
#ifdef _MSC_VER
#include <float.h>
#else
#include <math.h>
#include <cmath>
#endif
```

Thx. Cya.

**Comment by johnkslang** [comment]
`math.h` was changed to `cmath` a while back. If your file has a `math.h`, I suspect it's old version of interm.cpp.

**Comment by latot** [comment]
you are right, sorry..., this issue must back to ppsspp.

Thx.!
